# home:
#   path: /
#   controller: App\Controller\AppController::index
# login:
#   path: /login
#   controller: App\Controller\LoginController::index
# register:
#   path: /register
#   controller: App\Controller\RegisterController::index

controllers:
  resource: "../src/Controller/"
  type: annotation
